### ISSUE TITLE
Declarative models

### ISSUE THREAD

**Issue by SmileyChris** [radiac/nanodjango#6]
Crazy idea of looking in a `models` directory for models defined in yaml. Maybe this will make you vomit in your mouth a bit.

`models/person.yaml`:
```yaml
name: char_80 # charfield, max_length 80
age?: integer # nullable
country: # implicit charfield with choices
  - US
  - UK
  - other
score: # implicit integerfield with choices
  1: low
  2: medium
  3: high
best_friend?: person # foreignkeyfield, matching model name
login: =user # onetoonefield, matching model name
manager_of: users # manytomanyfield, matching model via verbose_plural_name (case insensitive)
created: datetime_now_add
updated: datetime_now

Meta: # meta options
  plural: people # simpler name for verbose_name_plural
  ordering:  # e.g. reverse name ordering
    - -name

Admin: # show in admin, can take options which translate directly to AdminModel properties
```
